version: 2
jobs:
  build:
    docker:
      - image: opuscapita/minsk-core-ci:cloud-toolbox
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Update submodules
          command: echo "Each run I became faster!"
          
workflows:
  version: 2
  minutely:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
